### ISSUE TITLE
Server Console Error

### ISSUE THREAD

**Issue by BaconGodOfDeath** [Osanchez/AnotherVeinMiner#1]
[error.txt](https://github.com/Osanchez/AnotherVeinMiner/files/9163365/error.txt)

**Comment by Osanchez** [comment]
@BaconGodOfDeath 

Is the error occurring when you try to mine an ore, or is it happening randomly? if it occurs to you based on your own action, a video will be greatly appreciated. Im not getting much from the error log. I see something is being destroyed, but im not sure if it is you or possibly a settler/worker

**Comment by Osanchez** [comment]
found one issue when attempting to break grass.

**Comment by Osanchez** [comment]
updated mod, please try v1.21 and let me know if you are still getting issues. I have not done as extensive testing on server as I have on local play

**Comment by BaconGodOfDeath** [comment]
It worked fine until I arrived at my settlement then it just stops responding. I would log back in and the second the villagers spread out it would crash. As if it were trying to automine for the NPCs as well.

So far the new build seems stable.

**Comment by Osanchez** [comment]
> So far the new build seems stable.


okay, will close this ticket. if there are any new issues or this same issue arises again please create a new issue with most recent log.
